# -*- mode: ruby -*-
# vi: set ft=ruby :
#
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  config.vm.hostname = "cn0"
#  config.vm.define  "cn1"

  config.vm.provider "libvirt" do | kvm |
    
  end

end
