# -*- mode: ruby -*-
# vi: set ft=ruby :
#
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "u3"

  config.vm.provider "libvirt" do | kvm |
    
  end

end
